### ISSUE TITLE
Доступ

### ISSUE THREAD

**Issue by fenixnow** [DoublesunRUS/ru.capralow.dt.bslls.validator#1]
Плагин можно установить в EDT через пункт "Установить новое ПО" указав сайт обновления http://capralow.ru/edt/bslls.validator/latest/

![image](https://user-images.githubusercontent.com/13418562/56579111-fdaf2a00-65d7-11e9-8e86-61fc5792c980.png)

**Comment by DoublesunRUS** [comment]
Поправил. Теперь при сборке в каталог репозитория копируется index.html с описанием, как установить плагин через EDT.
